name: Generate and Push Flash USDT Docs

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install groq

      - name: Generate MDX content
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          python generate_docs.py

      - name: Commit and push generated MDX file
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/flash-usdt.mdx
          git commit -m "Add generated content for Flash USDT docs" || echo "No changes to commit"
          git push

      - name: Upload MDX artifact
        uses: actions/upload-artifact@v4
        with:
          name: flash-usdt-docs
          path: docs/flash-usdt.mdx
