name: Documentation Generation and Deployment

on:
  push:
    branches:
      - main  # Trigger the workflow on push to main branch
  pull_request:
    branches:
      - main  # Trigger the workflow for PRs targeting the main branch

jobs:
  generate-documentation:
    runs-on: ubuntu-latest  # Run the job on an Ubuntu environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Check out the code from the repository

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use the Python 3.x environment

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install any dependencies from requirements.txt

    - name: Run Documentation Generation Script
      run: |
        python generate_documentation.py  # Run the Python script to generate the documentation

    - name: Deploy documentation to GitHub Pages
      run: |
        mkdir gh-pages
        cp documentation.html gh-pages/index.html  # Copy the generated documentation to the gh-pages folder
        cd gh-pages
        git init
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Deploy documentation"
        git branch -M main
        git remote add origin https://github.com/your-username/your-repository.git  # Replace with your repository URL
        git push -f origin main  # Push to the gh-pages branch

    - name: Cleanup
      run: |
        rm -rf gh-pages  # Clean up the generated folder after deployment

  # Optionally, you can add more jobs for testing or notifications if needed
